### PR TITLE
Add license

### LINKED ISSUE #4: Missing software license information
According to [the old site on Google Code](https://code.google.com/archive/p/talentledhack/), this software is GPL 3.0 licensed. However this license is missing from this repo.

### PR DESCRIPTION
**Pull request by h3xx**
According to https://code.google.com/archive/p/talentledhack/, GPL-3.0 is the license to use.

Closes #4

### CODE REVIEW

**Comment by trebmuh** [comment]
According to [the source](https://github.com/jeremysalwen/TalentedHack/blob/master/talentedhack.c), it's GPL v2.

**Comment by h3xx** [comment]
Updated; GPL 2.0 it is.

**Comment by h3xx** [comment]
Actually, it looks like it says it should be 3.0 compatible:

    either version 2 of the License, or (at your option) any later version.

I'm going to leave it as 3.0 since 2.0 is considered deprecated. It's up to the authors, really.

**Comment by trebmuh** [comment]
Yes, it is up to the author.

**Pull request merged**
